# Generated by Django 5.1.6 on 2025-12-03 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('idKaryawan', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'karyawan',
            },
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('idPelanggan', models.AutoField(primary_key=True, serialize=False)),
                ('namaPelanggan', models.CharField(max_length=50)),
                ('alamat', models.TextField()),
                ('noTelp', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pelanggan',
            },
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('idProduk', models.AutoField(primary_key=True, serialize=False)),
                ('namaProduk', models.CharField(max_length=50)),
                ('jenisProduk', models.CharField(choices=[('Bahan Baku', 'Bahan Baku'), ('Produk Jadi', 'Produk Jadi')], max_length=50)),
                ('harga', models.IntegerField()),
                ('stok', models.IntegerField()),
                ('satuan', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'produk',
            },
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('idPemesanan', models.AutoField(primary_key=True, serialize=False)),
                ('tanggalPemesanan', models.DateField()),
                ('totalPemesanan', models.IntegerField(default=0)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Diproses', 'Diproses'), ('Dikirim', 'Dikirim'), ('Selesai', 'Selesai'), ('Dibatalkan', 'Dibatalkan')], default='Diproses', max_length=50)),
                ('idPelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelanggan')),
            ],
            options={
                'db_table': 'pemesanan',
            },
        ),
        migrations.CreateModel(
            name='DetailPemesanan',
            fields=[
                ('idDetailPemesanan', models.AutoField(primary_key=True, serialize=False)),
                ('kuantiti', models.IntegerField()),
                ('subTotal', models.IntegerField()),
                ('idKoleksiPemesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pemesanan')),
                ('idProduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produk')),
            ],
            options={
                'db_table': 'detail_pemesanan',
            },
        ),
        migrations.CreateModel(
            name='Produksi',
            fields=[
                ('idProduksi', models.AutoField(primary_key=True, serialize=False)),
                ('tanggalProduksi', models.DateField()),
                ('jenisHasil', models.CharField(choices=[('Tahu', 'Tahu'), ('Tempe', 'Tempe')], max_length=50)),
                ('jumlahHasil', models.IntegerField()),
                ('satuanHasil', models.CharField(max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('idKaryawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.karyawan')),
            ],
            options={
                'db_table': 'produksi',
            },
        ),
        migrations.CreateModel(
            name='DetailProduksi',
            fields=[
                ('idDetail', models.AutoField(primary_key=True, serialize=False)),
                ('jumlahBahanTerpakai', models.IntegerField()),
                ('idProduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produk')),
                ('idProduksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produksi')),
            ],
            options={
                'db_table': 'detail_produksi',
            },
        ),
    ]
