# Generated by Django 5.2.9 on 2025-12-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemesanan',
            name='alamatPengiriman',
            field=models.TextField(default='Alamat belum diisi'),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='buktiBayar',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/'),
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='ongkosKirim',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produk',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='produk_images/'),
        ),
    ]
